import { test, expect } from '@playwright/test';

test.describe('calls', () => {
  test('calls add archived call', async ({ page }) => {
    await page.goto('https://qaweb.resgrid.dev/Account/LogOn');
    await page.getByPlaceholder('Username').click();
    await page.getByPlaceholder('Username').fill(process.env.PW_LOGIN_USERNAME);
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill(process.env.PW_LOGIN_PASSWORD);
    await page.getByRole('button', { name: 'Log On' }).click();
    await page.getByRole('link', { name: 'Calls' }).click();
    await expect(page.locator('#unitsStatusesList')).toContainText('Engine 1');
    await page.getByRole('link', { name: 'Archived Calls' }).click();
    await expect(page.locator('#addOldCall')).toContainText('Add Archived Call');
    await page.getByRole('link', { name: 'Add Archived Call' }).click();
    await expect(page.locator('ol')).toContainText('Add Archived Call');
    await page.getByPlaceholder('Name of the Call').click();
    await page.getByPlaceholder('Name of the Call').fill('Test Archive Call');
    await page.locator('#CallPriority').selectOption('1');
    await page.locator('#Call_Type').selectOption('MEDICAL');
    await page.locator('#Call_Type').selectOption('TRAFFIC ACCIDENT');
    await page.getByPlaceholder('Name of the Person Reporting').click();
    await page.getByPlaceholder('Name of the Person Reporting').fill('test1');
    await page.getByPlaceholder('Phone or Email address of the').click();
    await page.getByPlaceholder('Phone or Email address of the').fill('test2');
    await page.getByPlaceholder('CAD Id or Inbound Call System').click();
    await page.getByPlaceholder('CAD Id or Inbound Call System').fill('test3');
    await page.getByPlaceholder('Partner or Reference Number').click();
    await page.getByPlaceholder('Partner or Reference Number').fill('test4');
    await page.getByPlaceholder('Main or Parent External').click();
    await page.getByPlaceholder('Main or Parent External').fill('test5');
    await page.locator('#editor-container').getByRole('paragraph').click();
    await page.locator('#editor-container div').first().fill('test6');
    await page.locator('#editor-container2 div').first().click();
    await page.locator('#editor-container2 div').first().fill('test7');
    await page.getByPlaceholder('Map Book Page').click();
    await page.getByPlaceholder('Map Book Page').fill('test8');
    await page.getByPlaceholder('Full Address of the call (').click();
    await page.getByPlaceholder('Full Address of the call (').fill('123 Main Street, Reno Nev');
    await page.getByPlaceholder('Full Address of the call (').press('CapsLock');
    await page.getByPlaceholder('Full Address of the call (').fill('123 Main Street, Reno NevD');
    await page.getByPlaceholder('Full Address of the call (').press('CapsLock');
    await page.getByPlaceholder('Full Address of the call (').fill('123 Main Street, Reno Nev');
    await page.getByPlaceholder('Full Address of the call (').press('CapsLock');
    await page.getByPlaceholder('Full Address of the call (').fill('123 Main Street, Reno NevDA');
    await page.getByPlaceholder('Full Address of the call (').press('CapsLock');
    await page.getByPlaceholder('Full Address of the call (').fill('123 Main Street, Reno Nevada');
    await page.getByRole('link', { name: 'Find Address' }).click();
    await expect(page.getByRole('button', { name: 'Marker' })).toBeVisible();
    await page.getByPlaceholder('Notes about closing the call').click();
    await page.getByPlaceholder('Notes about closing the call').fill('test9');
    await page.getByRole('button', { name: 'Add Archived Call' }).click();
    await expect(page.locator('tbody')).toContainText('Test Archive Call');
  });
});